server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://cloud-register.e-lingcloud.com
spring:
  application:
    name: service-register
logging:
  file: /opt/service-register.log