server:
  port: 11001
eureka:
  server:
    #关闭自我保护
    enable-self-preservation: false
    #清理间隔(单位毫秒，默认是60*1000)
    eviction-interval-timer-in-ms: 60000
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.1.150:${server.port}/eureka/