server:
  port: 11001
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.1.150:${server.port}/eureka/
spring:
  application:
    name: service-register-dev
logging:
  file: /opt/cloud/logs/service-register.log