spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:  git@repos.e-lingcloud.com:component/com.eling.cloud.config.files.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://cloud-register.e-lingcloud.com/eureka/
server:
  port: 8080
logging:
  file: /opt/config-server.log