spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:  git@repos.e-lingcloud.com:component/com.eling.cloud.config.files.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.150:11001/eureka/
server:
  port: 11002
logging:
  file: /opt/cloud/logs/config-server.log