spring:
  cloud:
    config:
      server:
        git:
          uri:  http://repos.e-lingcloud.com/component/com.eling.cloud.config.files.git
          username: wuxian
          password: wx.4489268..
eureka:
  instance:
        preferIpAddress: true
        instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.1.150:11001/eureka/
server:
  port: 11002
logging:
  file: /opt/cloud/logs/config-server.log