spring:
  cloud:
    config:
      server:
        git:
          uri:  http://repos.e-lingcloud.com/component/com.eling.cloud.config.files.git
          username: wuxian
          password: wx.4489268..
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.32.2:8080/eureka/
server:
  port: 8080